
=CRASH REPORT==== 26-Jun-2015::19:31:37 ===
  crasher:
    initial call: gssample:init/1
    pid: <0.872.0>
    registered_name: gssample
    exception exit: {badarith,
                        [{gssample,handle_call,3,
                             [{file,"src/gssample.erl"},{line,41}]},
                         {gen_server,try_handle_call,4,
                             [{file,"gen_server.erl"},{line,607}]},
                         {gen_server,handle_msg,5,
                             [{file,"gen_server.erl"},{line,639}]},
                         {proc_lib,init_p_do_apply,3,
                             [{file,"proc_lib.erl"},{line,237}]}]}
      in function  gen_server:terminate/7 (gen_server.erl, line 804)
    ancestors: [wsserver_sup,<0.767.0>]
    messages: []
    links: [<0.871.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 147
  neighbours:

=SUPERVISOR REPORT==== 26-Jun-2015::19:31:37 ===
     Supervisor: {local,wsserver_sup}
     Context:    child_terminated
     Reason:     {badarith,
                     [{gssample,handle_call,3,
                          [{file,"src/gssample.erl"},{line,41}]},
                      {gen_server,try_handle_call,4,
                          [{file,"gen_server.erl"},{line,607}]},
                      {gen_server,handle_msg,5,
                          [{file,"gen_server.erl"},{line,639}]},
                      {proc_lib,init_p_do_apply,3,
                          [{file,"proc_lib.erl"},{line,237}]}]}
     Offender:   [{pid,<0.872.0>},
                  {name,gssample},
                  {mfargs,{gssample,start_link,[[]]}},
                  {restart_type,permanent},
                  {shutdown,brutal_kill},
                  {child_type,worker}]

